version: "3.8"

services:
  ecolook:
    build:
      context: .
    ports:
      - "8080:8080"
    depends_on:
      - db
    env_file:
      .env
    networks:
      - mynetwork

  db:
    image: postgres:latest
    restart: always
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge

volumes:
  postgres_data: